#version 20260401
#-----------------------------------------
mixed-port: 7890
tproxy-port: 9898
redir-port: 9797
mode: rule
allow-lan: true
unified-delay: false
tcp-concurrent: false
find-process-mode: strict
log-level: silent
ipv6: true
keep-alive-interval: 30
keep-alive-idle: 15
external-controller: 0.0.0.0:9090
external-ui: WebUI
external-ui-url: "https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip"


profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"

tun:
  enable: false
  stack: gvisor
  device: Meta
  udp-timeout: 300
  auto-route: true
  auto-redirect: false
  auto-detect-interface: true
  strict-route: false
  dns-hijack: 
    - any:53
    - tcp://any:53
  exclude-package:
    - com.android.settings
    - com.qti.qcc
    - com.sec.epdg
    - com.sec.imsservice
    - com.miui.packageinstaller
    
dns:
  enable: true
  ipv6: true
  ipv6-timeout: 300
  enhanced-mode: fake-ip
  fake-ip-filter:
    #- RULE-SET:中国域名
    - RULE-SET:Fake-IP-Filter
    - RULE-SET:自定义直连
    - RULE-SET:Private

  nameserver-policy:
    'rule-set:自定义直连,中国域名,Private':
      - 223.5.5.5
      - 119.29.29.29

    'rule-set:自定义代理,AI,Google': 
      - 8.8.8.8
      - 1.1.1.1

  nameserver:
    - 1.1.1.1#代理
    - 8.8.8.8#代理

  proxy-server-nameserver:
    - 223.5.5.5#中国网站
    - 119.29.29.29#中国网站

  proxy-server-nameserver-policy:

#------------------------------------------------
#机场订阅全局设置
pp: &pp
  type: http
  interval: 21600
  health-check:
    enable: true
    url: https://www.gstatic.com/generate_204
    interval: 3600
    timeout: 3000
    lazy: true
    expected-status: 204
  headers:
    User-Agent: "ClashMetaForAndroid/2.11.26"
    

proxy-providers:

  机场1:
    <<: *pp
    url: '订阅链接'
    path: ./proxy_providers/机场1.yaml

  机场2:
    <<: *pp
    url: '订阅链接'
    path: ./proxy_providers/机场2.yaml
    
#------------------------------------------------
proxy-groups:

  - name: 代理
    type: select
    include-all: true
    proxies:
      - 手动选择
      - 自动切换
     
  - name: 手动选择
    type: select
    include-all: true
    filter: '美国|USA|美國|us|US|United States'
    
  - name: 自动切换
    type: fallback
    include-all: true
    filter: '美国|USA|美國|us|US|United States'
    interval: 300
    lazy: true
    timeout: 3000
    max-failed-times: 5
    expected-status: 204
    url: 'https://www.gstatic.com/generate_204'

#------------------------------------------------

  - name: 人工智能
    type: select
    include-all: true
    proxies:
      - 手动选择
      - 自动切换
      
  - name: Google
    type: select
    proxies:
      - 手动选择
      - 代理
      - 自动切换

  - name: Emby服
    type: select
    proxies:
      - 手动选择
      - 代理
      - 自动切换
      - DIRECT

  - name: 中国网站
    type: select
    proxies:
      - DIRECT
      - 代理
    
  - name: 广告
    type: select
    proxies:
      - REJECT-DROP
      - PASS
           
#-------------------------------------------------------------------

rules:
  - PROCESS-NAME,cs2.exe,中国网站
  
  - RULE-SET,自定义代理,代理
  - RULE-SET,自定义直连,中国网站
  - RULE-SET,Private,DIRECT
  - RULE-SET,PrivateIP,DIRECT,no-resolve

  - RULE-SET,秋风广告规则,广告
  - RULE-SET,中国域名,中国网站
  - RULE-SET,中国IP,中国网站

  - RULE-SET,AI,人工智能
  - RULE-SET,Google,Google
  - RULE-SET,Emby,Emby服

  - MATCH,代理

#------------------------------------------------------------------------------
rm: &rm
  type: http
  behavior: domain
  format: mrs
  interval: 86400

ri: &ri
  type: http
  behavior: ipcidr
  format: mrs
  interval: 86400
  
rm_yaml: &rm_yaml
  type: http
  behavior: domain
  format: yaml
  interval: 86400

rule-providers:

  秋风广告规则:
    <<: *rm
    path: ./rules/AWAvenue-Ads-Rule-Clash.mrs
    url: https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Clash.mrs

  自定义直连:
    <<: *rm_yaml
    path: ./rules/自定义直连.yaml
    url: https://github.com/ARIALUX-droid/mih-lux/raw/refs/heads/main/rule/自定义直连.yaml
    
  自定义代理:
    <<: *rm_yaml
    path: ./rules/自定义代理.yaml
    url: https://github.com/ARIALUX-droid/mih-lux/raw/refs/heads/main/rule/自定义代理.yaml
    
  AI:
    <<: *rm
    path: ./rules/AI.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-!cn.mrs

  Google:
    <<: *rm
    path: ./rules/Google.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs

  Emby:
    <<: *rm
    path: ./rules/Emby.mrs
    url: https://github.com/666OS/rules/raw/release/mihomo/domain/Emby.mrs

  Private:
    <<: *rm
    path: ./rules/Private.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs
    
  PrivateIP:
    <<: *ri
    path: ./rules/PrivateIP.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs

  Fake-IP-Filter:
    <<: *rm
    path: ./rules/Fake-IP-Filter.mrs
    url: https://github.com/DustinWin/ruleset_geodata/raw/refs/heads/mihomo-ruleset/fakeip-filter.mrs

  中国域名:
    <<: *rm
    path: ./rules/中国域名.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs

  中国IP:
    <<: *ri
    path: ./rules/中国IP.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs
